# Generated by Django 2.2.5 on 2019-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('thumb', models.URLField()),
                ('description', models.CharField(max_length=300)),
                ('thumbnail200', models.URLField()),
                ('thumbnail180', models.URLField()),
                ('direct_url', models.URLField()),
                ('date_added', models.DateField()),
                ('site_name', models.CharField(max_length=300)),
            ],
        ),
    ]
