# Generated by Django 2.2.5 on 2019-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.CharField(max_length=300),
        ),
    ]
