# Generated by Django 2.2.5 on 2019-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_auto_20190906_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.CharField(max_length=50),
        ),
    ]
