# Generated by Django 2.2.5 on 2019-09-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_auto_20190906_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='thumbnail180',
        ),
    ]
