# Generated by Django 2.2.5 on 2019-09-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0005_bestsites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestSites',
            new_name='BestSite',
        ),
    ]
