# Generated by Django 2.2.5 on 2019-09-07 12:31

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0007_auto_20190907_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysmc',
            name='thumb',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/pic'),
        ),
    ]
