# Generated by Django 2.2.5 on 2019-09-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0008_auto_20190907_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysmc',
            name='thumb',
            field=models.FileField(upload_to='media/pic'),
        ),
    ]
