# Generated by Django 2.2.5 on 2019-09-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0011_picturepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='PicturePost',
        ),
    ]
