# Generated by Django 2.2.5 on 2019-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0015_photosession_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosession',
            name='img',
            field=models.ImageField(upload_to='Photosession'),
        ),
    ]
