# Generated by Django 2.2.5 on 2019-09-10 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0017_auto_20190910_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='photo',
            name='image10',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image7',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image8',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image9',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/(Photo.id)'),
            preserve_default=False,
        ),
    ]
