# Generated by Django 2.2.5 on 2019-09-10 11:56

from django.db import migrations, models
import galleryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0018_auto_20190910_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image9',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image1',
            field=models.ImageField(upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image2',
            field=models.ImageField(upload_to=galleryapp.models.get_member_upload_to),
        ),
    ]
