# Generated by Django 2.2.5 on 2019-09-10 12:57

from django.db import migrations, models
import galleryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0020_auto_20190910_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image1',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image10',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image11',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image12',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image13',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image14',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image15',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image16',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image17',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image18',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image19',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image2',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image20',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image3',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image4',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image5',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image6',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image7',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image8',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image9',
            field=models.ImageField(blank=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
    ]
