# Generated by Django 2.2.5 on 2019-09-10 13:22

from django.db import migrations, models
import galleryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0021_auto_20190910_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to=galleryapp.models.get_member_upload_to),
        ),
    ]
