# Generated by Django 2.2.5 on 2019-09-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0022_auto_20190910_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image9',
        ),
    ]
