# Generated by Django 2.2.5 on 2019-09-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0023_auto_20190910_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
